baseURL: 'https://lucent-granita-b62a26.netlify.app/'
title: 'My New Hugo Site'
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true

primary_color: red
params:
  primary_color: "red"
