backend:
  name: git-gateway
  branch: main
media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
collections: 
  - name: "english"
    label: "english"
    files:
      - file: "content/promotions.md"
        label: "Promotions Page"
        name: "promotions"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Promotions", name: "promotions", widget: "object", fields: [{label: "promo_items", name: "promo_items", widget: "object", fields: [{label: "title", name: "title", widget: "string"}, {label: "img", name: "img", widget: "image"}, {label: "date", name: "date", widget: "string"}, {label: "btn_link", name: "btn_link", widget: "string"},]}]}
             


